version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
#      - mvn test
    post_build:
      commands:
        - echo Build completed on `date`
        - ls
        - mvn package
        - ls
artifacts:
  files:
    - customer-service/target/customer-service-0.0.1-SNAPSHOT.jar
    - order-service/target/order-service-0.0.1-SNAPSHOT.jar
    - product-service/target/product-service-0.0.1-SNAPSHOT.jar
    - eureka-server/target/eureka-server-0.0.1-SNAPSHOT.jar
  discard-paths: yes